
final _gmtList = [
  '(GMT-01) Azores',
  '(GMT-01) Cape Verde Islands',
  '(GMT-02) Mid-Atlantic',
  '(GMT-03) Brasilia',
  '(GMT-03) Buenos Aires',
  '(GMT-03) Greenland',
  '(GMT-03:30) Newfoundland',
  '(GMT-04) Atlantic',
  '(GMT-04) Caracas',
  '(GMT-04) Manaus',
  '(GMT-04) Santiago',
  '(GMT-05) Bogota, Lima, Quito',
  '(GMT-05) Eastern',
  '(GMT-05) Indiana (East)',
  '(GMT-06) Central America',
  '(GMT-06) Central',
  '(GMT-06) Guadalajara, Mexico City, Monterrey',
  '(GMT-06) Saskatchewan',
  '(GMT-07) Arizona',
  '(GMT-07) Mountain',
  '(GMT-08) Pacific',
  '(GMT-09) Alaska',
  '(GMT-10) Hawaii',
  '(GMT-11) Midway Island, Samoa',
  '(GMT+01) Amsterdam, Berlin, Bern, Rome, Stockholm',
  '(GMT+01) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
  '(GMT+01) Brussels, Copenhagen, Madrid, Paris',
  '(GMT+01) Sarajevo, Skopje, Warsaw, Zagreb',
  '(GMT+01) West Central Africa',
  '(GMT+02) Athens, Bucharest, Istanbul',
  '(GMT+02) Cairo Africa/Cairo',
  '(GMT+02) Harare, Pretoria',
  '(GMT+02) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius',
  '(GMT+02) Jerusalem',
  '(GMT+02) Minsk',
  '(GMT+02) Windhoek',
  '(GMT+03) Baghdad',
  '(GMT+03) Kuwait, Riyadh',
  '(GMT+03) Moscow, St. Petersburg, Volgograd',
  '(GMT+03) Nairobi',
  '(GMT+03:30) Tehran',
  '(GMT+04) Abu Dhabi, Muscat',
  '(GMT+04) Baku',
  '(GMT+04) Tblisi',
  '(GMT+04) Yerevan',
  '(GMT+04:30) Kabul',
  '(GMT+05) Ekaterinburg',
  '(GMT+05) Islamabad, Karachi, Tashkent',
  '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi',
  '(GMT+05:45) Kathmandu Asia/Kathmandu',
  '(GMT+06) Almaty, Novosibirsk',
  '(GMT+06) Astana, Dhaka',
  '(GMT+06) Sri Jayawardenepura',
  '(GMT+06:30) Yangon',
  '(GMT+07) Bangkok, Hanoi, Jakarta',
  '(GMT+07) Krasnoyarsk',
  '(GMT+08) Beijing, Chongqing, Hong Kong SAR, Urumqi',
  '(GMT+08) Irkutsk, Ulaanbaatar',
  '(GMT+08) Kuala Lumpur, Singapore',
  '(GMT+08) Perth',
  '(GMT+08) Taipei',
  '(GMT+09) Osaka, Sapporo, Tokyo',
  '(GMT+09) Seoul',
  '(GMT+09) Yakutsk',
  '(GMT+09:30) Adelaide ',
  '(GMT+09:30) Darwin ',
  '(GMT+10) Brisbane',
  '(GMT+10) Canberra, Melbourne, Sydney',
  '(GMT+10) Guam, Port Moresby',
  '(GMT+10) Hobart',
  '(GMT+10) Vladivostok',
  '(GMT+11) Magadan, Solomon Islands, New Caledonia',
  '(GMT+12) Auckland, Wellington',
  '(GMT+12) Fiji Islands, Kamchatka, Marshall Islands',
  '(GMT+13) Nuku',
];

